field: ecad64de-f06b-4d1c-8c67-951bc9432165 # ContactformulierLinkGroup
fieldLayouts:
  b44923b6-a5ca-448a-b762-672c3ee71646:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e2acc153-09da-46ae-861a-bfd4fb607a0f # Contact
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d36d836-bd92-434e-a743-489765803d9a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 155ef2b0-5660-4610-8b6c-9354eebacf4f
        userCondition: null
fields:
  e2acc153-09da-46ae-861a-bfd4fb607a0f: # Contact
    columnSuffix: kezqhoqf
    contentColumnType: string
    fieldGroup: null
    handle: contact
    instructions: null
    name: Contact
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: false
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: asset
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: true
        email:
          allowAliases: false
          disableValidation: false
          enabled: true
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: true
        url:
          allowAliases: false
          disableValidation: false
          enabled: true
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
handle: contact
name: Contact
sortOrder: 1
