fieldLayouts:
  f86d6ec7-9c5c-4e4b-b822-67d3c70abf3f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8aa21f55-c213-400d-b7f7-dbc27d68d32f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 18f61b71-9a64-4293-9a38-968dd55c5e91 # ContactPaginaTekst
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff40149d-8a8a-4c62-a977-a281e9ee9561
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ecad64de-f06b-4d1c-8c67-951bc9432165 # ContactformulierLinkGroup
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e8ef946-37fd-4f9e-b40f-f97bc2a768e1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8803d388-cb75-436b-8945-939e80d0adc1
        userCondition: null
handle: contactformulier
hasTitleField: true
name: Contactformulier
section: 190f069b-edfb-45b9-9fc6-bedf27af04b5 # Contactpagina
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
