fieldLayouts:
  f2ff4a07-8f72-4d6f-b3c7-d442ec8b6587:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 30ee4b62-8cee-470e-a60a-0b1e670ea23a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ecad64de-f06b-4d1c-8c67-951bc9432165 # ContactformulierLinkGroup
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12ff3314-827a-4a5f-b45d-82bb032a17f2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8d4902c5-1147-42aa-8930-b0f5cd0d9b98
        userCondition: null
handle: contactformulierLink
hasTitleField: true
name: 'Contactformulier Link'
section: 190f069b-edfb-45b9-9fc6-bedf27af04b5 # Contactpagina
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
