fieldLayouts:
  20cc3e40-8661-4f3e-a7ea-f70e5edbb397:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 83ef56b7-287e-479f-a5e1-7dba540dbba3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b9744da2-0f38-4a28-8e06-55ca5eb8a847 # Nieuwspaginatekst
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b9921f7-26cb-4f72-8ab9-d87cace044e7
            userCondition: null
            warning: null
            width: 100
        name: 'tekst 1'
        uid: 0e18c456-e29c-45b9-a0d2-20f2b0d6746d
        userCondition: null
handle: Nieuwspagina
hasTitleField: true
name: Nieuwspagina
section: 806c152e-3094-4e0c-b72f-69950132c3ff # Nieuws
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
