fieldLayouts:
  35a1b5de-1881-494f-99a9-64b1db4af649:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b35ee3c7-2cbb-4cb9-956d-8ac9647218f4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b9744da2-0f38-4a28-8e06-55ca5eb8a847 # Nieuwspaginatekst 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab87626f-8e8e-4e89-a5dc-2d40424ac187
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5355a89f-7195-41ad-9497-27ec48eb87ec
        userCondition: null
handle: nieuwspaginatekst1
hasTitleField: true
name: 'Nieuwspaginatekst 1'
section: 806c152e-3094-4e0c-b72f-69950132c3ff # Nieuwspagina
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
