fieldLayouts:
  de6a5a97-c4ce-41a8-b8d5-a82880b457a9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bde8b16b-a104-490d-88c4-bde0d1af4753
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7282b0d6-cd9c-452e-9486-93188a764195 # Nieuwspaginatekst 3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0afa32eb-b5d7-45cb-8609-5df3c694f497
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4b76f413-eccd-45b7-aac8-2fb9676a244e
        userCondition: null
handle: nieuwspaginatekst3
hasTitleField: true
name: 'Nieuwspaginatekst 3'
section: 806c152e-3094-4e0c-b72f-69950132c3ff # Nieuwspagina
sortOrder: 4
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
