fieldLayouts:
  73950428-8376-42a2-b2ac-1c7de9681441:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 32810fdd-594b-4119-b38b-29d8f856b265
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fcdfa729-1e41-4d6f-a28f-fb7a3ee2ddf6 # Nieuwspaginatekst 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3eac0666-951d-4ecc-a11b-d0b6e63f4bb7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5a6e41fb-07ed-46f5-b91e-601e6d080265
        userCondition: null
handle: nieuwspaginatekst2
hasTitleField: true
name: 'Nieuwspaginatekst 2'
section: 806c152e-3094-4e0c-b72f-69950132c3ff # Nieuwspagina
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
