fieldLayouts:
  e7989bba-76f3-4554-918f-d1ad418f6064:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ba0c7541-43d5-4543-9523-ee9efad75a4c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ac566931-ad44-4552-abdf-bba91d4899b9
        userCondition: null
fs: assets
handle: public
name: public
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: '@root/web/assets'
