columnSuffix: null
contentColumnType: string
fieldGroup: 90734f86-d637-45c2-8dff-7265a51843ca # Common
handle: contactformulierlinkgroup
instructions: null
name: ContactformulierLinkGroup
searchable: false
settings:
  contentTable: '{{%matrixcontent_contactformulierlinkgroup}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
