defaultPlacement: end
enableVersioning: true
handle: homePage
name: 'Home page'
propagationMethod: all
siteSettings:
  b5f9038a-af7a-4077-b032-b9ae4a5977d0: # Stage
    enabledByDefault: true
    hasUrls: true
    template: homepage/homepage.twig
    uriFormat: __home__
type: single
