defaultPlacement: end
enableVersioning: true
handle: mailer
name: Mailer
propagationMethod: all
siteSettings:
  b5f9038a-af7a-4077-b032-b9ae4a5977d0: # Stage
    enabledByDefault: true
    hasUrls: true
    template: mailer/_entry
    uriFormat: 'mailer/{slug}'
type: channel
