defaultPlacement: end
enableVersioning: true
handle: nieuwspagina
name: Nieuws
propagationMethod: all
siteSettings:
  b5f9038a-af7a-4077-b032-b9ae4a5977d0: # Stage
    enabledByDefault: true
    hasUrls: true
    template: homepage/nieuwspagina.twig
    uriFormat: 'nieuws/{slug}'
type: channel
